// layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navigationbar from "./Navigationbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navigationbar /> */}
        <div className="bg-zinc-900 min-h-screen w-full text-white">
          {children}
        </div>
      </body>
    </html>
  );
}
